# Generated by Django 4.1.3 on 2022-11-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=128)),
                ('interested_in', models.CharField(choices=[('1', 'Option1'), ('2', 'Option2')], max_length=128)),
                ('user_agreement', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'web_contacts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customers/')),
            ],
            options={
                'db_table': 'web_customers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('feature_email', models.BooleanField(default=False)),
                ('feature_admin', models.BooleanField(default=False)),
                ('feature_list', models.BooleanField(default=False)),
                ('feature_data', models.BooleanField(default=False)),
                ('feature_planning', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'web_plans',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='services/')),
            ],
            options={
                'db_table': 'web_services',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to='teams/')),
                ('name', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('facebook_url', models.CharField(max_length=128)),
                ('twitter_url', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'web_teams',
                'ordering': ['-id'],
            },
        ),
    ]
